/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarDatePicker: typeof import('@varlet/ui')['_DatePickerComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarPullRefresh: typeof import('@varlet/ui')['_PullRefreshComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}
